import { f } from '../config/firebase';
const { collection, query, where, getDocs, limit, addDoc, serverTimestamp } = f;
import { db } from '../config/firebase';
import { GrowthMetrics, GrowthIntelligenceService } from './GrowthIntelligenceService';
import { MarketplaceExpansionService, CityExpansionMetrics } from './MarketplaceExpansionService';
import { DemandForecastService, ProductDemandInsight } from './DemandForecastService';
import { NotificationService } from './NotificationService';
import { loggingService } from './LoggingService';

export interface AutonomousAction {
  id?: string;
  action: string;
  reason: string;
  impact: string;
  timestamp: any;
  status: 'executed' | 'failed' | 'skipped';
  metadata?: any;
}

export class AutonomousGrowthOrchestrator {
  private static instance: AutonomousGrowthOrchestrator;
  private growthIntel: GrowthIntelligenceService;
  private marketplace: MarketplaceExpansionService;
  private demandForecast: DemandForecastService;
  // @ts-ignore
  private notifications: NotificationService;

  private readonly DAILY_ACTION_LIMIT = 5;
  private readonly ANTI_SPAM_HOURS = 24;

  private constructor() {
    this.growthIntel = GrowthIntelligenceService.getInstance();
    this.marketplace = MarketplaceExpansionService.getInstance();
    this.demandForecast = DemandForecastService.getInstance();
    this.notifications = NotificationService.getInstance();
    loggingService.info('AutonomousGrowthOrchestrator: Orquestrador autônomo iniciado');
  }

  public static getInstance(): AutonomousGrowthOrchestrator {
    if (!AutonomousGrowthOrchestrator.instance) {
      AutonomousGrowthOrchestrator.instance = new AutonomousGrowthOrchestrator();
    }
    return AutonomousGrowthOrchestrator.instance;
  }

  /**
   * Executa o ciclo completo de decisão autônoma
   */
  public async runOrchestrationCycle(): Promise<void> {
    try {
      loggingService.info('🤖 [Autonomous] Iniciando ciclo de decisão autônoma...');

      // 0. Verificar limites de segurança
      const canAct = await this.checkDailyLimit();
      if (!canAct) {
        loggingService.warn('🤖 [Autonomous] Limite diário de ações atingido. Pulando ciclo.');
        return;
      }

      // 1. Obter dados de inteligência
      const metrics = await this.growthIntel.calculateMetrics();
      const cityMetrics = await this.marketplace.getCityMetrics();
      const demandInsights = await this.demandForecast.generateDemandInsights();

      // 2. Executar Decisões
      await Promise.all([
        this.decideOnRevenueDrop(metrics),
        this.decideOnCityExpansion(cityMetrics),
        this.decideOnStockOptimization(demandInsights),
        this.decideOnReengagement()
      ]);

      loggingService.info('🤖 [Autonomous] Ciclo de decisão concluído.');
    } catch (error: any) {
      loggingService.error('🤖 [Autonomous] Erro no ciclo de orquestração', { error: error.message });
    }
  }

  /**
   * ETAPA 1: Recuperação de Queda de Conversão/Receita
   */
  private async decideOnRevenueDrop(metrics: GrowthMetrics): Promise<void> {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const yesterdayStr = yesterday.toISOString().split('T')[0];

    const q = query(collection(db, 'growth_metrics_daily'), where('date', '==', yesterdayStr), limit(1));
    const snap = await getDocs(q);

    if (!snap.empty) {
      const prev = snap.docs[0].data() as unknown as GrowthMetrics;
      
      // Queda de Conversão > 20% ou Receita > 15%
      if (metrics.conversionRate < prev.conversionRate * 0.8 || metrics.averageTicket < prev.averageTicket * 0.85) {
        const reason = metrics.conversionRate < prev.conversionRate * 0.8 ? 'low_conversion' : 'low_revenue';
        
        // Anti-spam
        const alreadyActed = await this.checkAntiSpam('AUTO_RECOVERY_COUPON');
        if (alreadyActed) return;

        loggingService.info(`🤖 [Autonomous] Detectada queda em ${reason}. Executando recuperação.`);

        // AÇÃO: Criar Cupom Automático
        const couponCode = `RECUPERA${Math.floor(Math.random() * 1000)}`;
        await addDoc(collection(db, 'coupons'), {
          code: couponCode,
          discountType: 'percentage',
          value: 15,
          active: true,
          description: 'Desconto automático para incentivar retorno',
          createdAt: serverTimestamp(),
          autoGenerated: true
        });

        // AÇÃO: Disparar Push para usuários ativos (amostragem para segurança)
        // Em um cenário real, usaríamos um segmento do OneSignal
        await this.logAction({
          action: 'coupon_created',
          reason: reason,
          impact: 'estimated_revenue_increase_10pct',
          status: 'executed',
          timestamp: serverTimestamp(),
          metadata: { couponCode }
        });
      }
    }
  }

  /**
   * ETAPA 2: Expansão Automática por Cidade
   */
  private async decideOnCityExpansion(cities: CityExpansionMetrics[]): Promise<void> {
    for (const city of cities) {
      if (city.opportunityLevel === 'EXPANSION_OPPORTUNITY') {
        const alreadyActed = await this.checkAntiSpam(`CITY_ACTIVATE_${city.cityId}`);
        if (alreadyActed) continue;

        loggingService.info(`🤖 [Autonomous] Oportunidade detectada em ${city.cityName}. Ativando cidade.`);

        // AÇÃO: Ativar Cidade e Gerar Incentivo
        await this.marketplace.activateCity(city.cityId);

        await this.logAction({
          action: 'city_expansion_activated',
          reason: 'high_demand_zero_producers',
          impact: 'market_share_growth',
          status: 'executed',
          timestamp: serverTimestamp(),
          metadata: { cityId: city.cityId, cityName: city.cityName }
        });
      }
    }
  }

  /**
   * ETAPA 3: Otimização de Estoque (Baixa venda + Alto estoque)
   */
  private async decideOnStockOptimization(insights: ProductDemandInsight[]): Promise<void> {
    for (const insight of insights) {
      // Se tendência é DOWN e score baixo, mas temos muito estoque (repositionRequired costuma indicar falta, 
      // mas aqui invertemos para "queima de estoque" se necessário)
      if (insight.trend === 'DOWN' && insight.score < 2) {
        const alreadyActed = await this.checkAntiSpam(`STOCK_PROMO_${insight.productId}`);
        if (alreadyActed) continue;

        loggingService.info(`🤖 [Autonomous] Baixa demanda para ${insight.productName}. Gerando promoção de queima.`);

        await this.logAction({
          action: 'product_promotion_triggered',
          reason: 'low_demand_stock_optimization',
          impact: 'stock_turnover_improvement',
          status: 'executed',
          timestamp: serverTimestamp(),
          metadata: { productId: insight.productId, productName: insight.productName }
        });
      }
    }
  }

  /**
   * ETAPA 4: Reengajamento Inteligente
   */
  private async decideOnReengagement(): Promise<void> {
    // Ações de reengajamento já são processadas via GrowthService, 
    // mas o orquestrador pode intensificar se a retenção geral cair.
    const metrics = await this.growthIntel.calculateMetrics();
    if (metrics.retentionRate < 30) {
      loggingService.info('🤖 [Autonomous] Retenção global baixa. Intensificando reengajamento.');
      // Ação adicional: Notificar Admin para revisar estratégia de produto
    }
  }

  /**
   * SEGURANÇA: Limite de ações por dia
   */
  private async checkDailyLimit(): Promise<boolean> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    
    const q = query(
      collection(db, 'autonomous_actions_log'),
      where('timestamp', '>=', today),
      where('status', '==', 'executed')
    );
    
    const snap = await getDocs(q);
    return snap.docs.length < this.DAILY_ACTION_LIMIT;
  }

  /**
   * SEGURANÇA: Anti-Spam por ação específica
   */
  private async checkAntiSpam(actionKey: string): Promise<boolean> {
    const hoursAgo = new Date(Date.now() - this.ANTI_SPAM_HOURS * 60 * 60 * 1000);
    
    const q = query(
      collection(db, 'autonomous_actions_log'),
      where('metadata.actionKey', '==', actionKey),
      where('timestamp', '>=', hoursAgo),
      limit(1)
    );
    
    const snap = await getDocs(q);
    return !snap.empty;
  }

  /**
   * LOG: Registrar ação autônoma
   */
  private async logAction(action: AutonomousAction): Promise<void> {
    await addDoc(collection(db, 'autonomous_actions_log'), {
      ...action,
      metadata: {
        ...action.metadata,
        actionKey: action.metadata?.actionKey || action.action // Para anti-spam
      }
    });
  }
}
