module.exports = {
  isDevice: jest.fn().mockReturnValue(true),
  brand: 'Test Brand',
  manufacturer: 'Test Manufacturer',
  modelName: 'Test Model',
  modelId: 'test-model-id',
  designName: 'test-design',
  productName: 'Test Product',
  deviceYearClass: 2023,
  totalMemory: 8192,
  supportedCpuArchitectures: ['arm64'],
  osName: 'Android',
  osVersion: '13.0.0',
  osBuildId: 'test-build-id',
  osInternalBuildId: 'test-internal-build-id',
  osBuildFingerprint: 'test-fingerprint',
  platformApiLevel: 33,
  deviceName: 'Test Device',
};
