#!/usr/bin/env bash

# 🛡️ scripts/load-env.sh - O Sincronizador de Variáveis EXPO_PUBLIC_*
# Missão: Mapear e exportar automaticamente todas as variáveis necessárias para o runtime do Expo no CI.

echo "🔍 [LOAD-ENV] Iniciando mapeamento automático de variáveis..."

# Lista de variáveis EXPO_PUBLIC_* extraídas do src/config/env.ts
EXPO_PUBLIC_VARS=(
  "EXPO_PUBLIC_API_URL"
  "EXPO_PUBLIC_PROJECT_ID"
  "EXPO_PUBLIC_APP_NAME"
  "EXPO_PUBLIC_FIREBASE_API_KEY"
  "EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN"
  "EXPO_PUBLIC_FIREBASE_PROJECT_ID"
  "EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET"
  "EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
  "EXPO_PUBLIC_FIREBASE_APP_ID"
  "EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID"
  "EXPO_PUBLIC_FIREBASE_DATABASE_URL"
  "EXPO_PUBLIC_FIREBASE_VAPID_KEY"
  "EXPO_PUBLIC_ONESIGNAL_APP_ID"
  "EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY"
  "EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID"
  "EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID"
  "EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID"
  "EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID"
  "EXPO_PUBLIC_MONITORING_REMOTE_ENABLED"
)

# Outras variáveis críticas do EAS/Apple
CRITICAL_VARS=(
  "EXPO_TOKEN"
  "EXPO_ASC_KEY_ID"
  "EXPO_ASC_ISSUER_ID"
  "EXPO_ASC_PRIVATE_KEY"
  "EXPO_ASC_PRIVATE_KEY_BASE64"
  "EXPO_APPLE_TEAM_ID"
  "GOOGLE_SERVICES_INFO_PLIST_BASE64"
)

ALL_VARS=("${EXPO_PUBLIC_VARS[@]}" "${CRITICAL_VARS[@]}")

COUNT=0
MISSING=0

# 1. Fallbacks para variáveis ausentes (Evitar quebras triviais)
: "${EXPO_PUBLIC_PROJECT_ID:=6090106b-e327-4744-bce5-9ddb0d037045}"
: "${EXPO_PUBLIC_APP_NAME:=Açucaradas Encomendas}"

# 2. Geração do arquivo .env.local para o build LOCAL
# O Expo CLI lê automaticamente o .env.local durante o prebuild/build.
ENV_FILE=".env.local"
echo "📝 [LOAD-ENV] Gerando $ENV_FILE para o build LOCAL..."
echo "# Generated by scripts/load-env.sh" > "$ENV_FILE"

for VAR_NAME in "${ALL_VARS[@]}"; do
    # Verifica se a variável existe no ambiente (GitHub Secrets injetados como ENV)
    if [ -n "${!VAR_NAME:-}" ]; then
        # Adicionar ao arquivo .env.local se for prefixada com EXPO_PUBLIC_
        if [[ "$VAR_NAME" == EXPO_PUBLIC_* ]]; then
            echo "$VAR_NAME=${!VAR_NAME}" >> "$ENV_FILE"
        fi

        # Se estivermos no GitHub Actions, garantir que ela esteja no GITHUB_ENV para passos subsequentes
        if [ -n "${GITHUB_ENV:-}" ]; then
            # Tratar multiline APENAS se houver quebra de linha real (Ex: PEM Key)
            if [[ "${!VAR_NAME}" == *$'\n'* ]]; then
                echo "$VAR_NAME<<EOF" >> "$GITHUB_ENV"
                echo "${!VAR_NAME}" >> "$GITHUB_ENV"
                echo "EOF" >> "$GITHUB_ENV"
            else
                # Exportar de forma segura para o GITHUB_ENV
                echo "$VAR_NAME=${!VAR_NAME}" >> "$GITHUB_ENV"
            fi
        fi
        COUNT=$((COUNT + 1))
    else
        # Apenas loga como aviso, o validate-env.js fará o fail fast definitivo
        echo "⚠️ [WARN] Variável $VAR_NAME não encontrada no ambiente."
        MISSING=$((MISSING + 1))
    fi
done

echo "✅ [LOAD-ENV] Arquivo $ENV_FILE gerado com sucesso."
echo "✅ [LOAD-ENV] Mapeamento concluído: $COUNT variáveis carregadas, $MISSING ausentes."
echo "------------------------------------------------------------"
