name: IOS AUTO BUILD

on:
  push:
    branches:
      - release-stable-1168

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Force Correct Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version
          xcodebuild -showsdks

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Type check
        run: npm run type-check

      - name: Show Xcode
        run: xcodebuild -version